In [1]:
from sklearn.feature_extraction.text import CountVectorizer

docs = ["I love NLP", "NLP loves machine learning", "I enjoy learning"]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

vectorizer.get_feature_names_out(), X.toarray()


(array(['enjoy', 'learning', 'love', 'loves', 'machine', 'nlp'],
       dtype=object),
 array([[0, 0, 1, 0, 0, 1],
        [0, 1, 0, 1, 1, 1],
        [1, 1, 0, 0, 0, 0]]))

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X2 = tfidf.fit_transform(docs)

tfidf.get_feature_names_out(), X2.toarray()


(array(['enjoy', 'learning', 'love', 'loves', 'machine', 'nlp'],
       dtype=object),
 array([[0.        , 0.        , 0.79596054, 0.        , 0.        ,
         0.60534851],
        [0.        , 0.42804604, 0.        , 0.5628291 , 0.5628291 ,
         0.42804604],
        [0.79596054, 0.60534851, 0.        , 0.        , 0.        ,
         0.        ]]))

In [3]:
!pip install gensim


   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   - -------------------------------------- 0.8/24.4 MB 2.8 MB/s eta 0:00:09
   -- ------------------------------------- 1.3/24.4 MB 2.8 MB/s eta 0:00:09
   ---- ----------------------------------- 2.9/24.4 MB 4.5 MB/s eta 0:00:05
   ------ --------------------------------- 3.7/24.4 MB 4.0 MB/s eta 0:00:06
   ------- -------------------------------- 4.7/24.4 MB 4.1 MB/s eta 0:00:05
   --------- ------------------------------ 6.0/24.4 MB 4.5 MB/s eta 0:00:05
   ------------ --------------------------- 7.6/24.4 MB 4.8 MB/s eta 0:00:04
   --------------- ------------------------ 9.2/24.4 MB 5.1 MB/s eta 0:00:03
   ----------------- ---------------------- 10.5/24.4 MB 5.4 MB/s eta 0:00:03
   ----------------- ---------------------- 10.5/24.4 MB 5.4 MB/s eta 0:00:03
   ----------------- ---------------------- 10.5/24.4 MB 5.4 MB/s eta 0:00:03
   -------

In [4]:
from gensim.models import Word2Vec

sentences = [
    ["I", "love", "NLP"],
    ["NLP", "loves", "machine", "learning"],
    ["I", "enjoy", "learning"]
]

model = Word2Vec(sentences, vector_size=50, window=3, min_count=1)


C:\Users\KRISHNENDU\anaconda3\envs\etl-pipeline\lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(


In [5]:
model.wv["learning"]


array([-1.0724545e-03,  4.7286271e-04,  1.0206699e-02,  1.8018546e-02,
       -1.8605899e-02, -1.4233618e-02,  1.2917745e-02,  1.7945977e-02,
       -1.0030856e-02, -7.5267432e-03,  1.4761009e-02, -3.0669428e-03,
       -9.0732267e-03,  1.3108104e-02, -9.7203208e-03, -3.6320353e-03,
        5.7531595e-03,  1.9837476e-03, -1.6570430e-02, -1.8897636e-02,
        1.4623532e-02,  1.0140524e-02,  1.3515387e-02,  1.5257311e-03,
        1.2701781e-02, -6.8107317e-03, -1.8928028e-03,  1.1537147e-02,
       -1.5043275e-02, -7.8722071e-03, -1.5023164e-02, -1.8600845e-03,
        1.9076237e-02, -1.4638334e-02, -4.6675373e-03, -3.8754821e-03,
        1.6154874e-02, -1.1861792e-02,  9.0324880e-05, -9.5074680e-03,
       -1.9207101e-02,  1.0014586e-02, -1.7519170e-02, -8.7836506e-03,
       -7.0199967e-05, -5.9236289e-04, -1.5322480e-02,  1.9229487e-02,
        9.9641159e-03,  1.8466286e-02], dtype=float32)

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

v1 = model.wv["love"]
v2 = model.wv["loves"]

cosine_similarity([v1], [v2])


array([[0.18339458]], dtype=float32)

In [7]:
model.wv.most_similar("learning")


[('I', 0.1267007291316986),
 ('NLP', 0.042373016476631165),
 ('loves', 0.012442173436284065),
 ('enjoy', -0.01447527389973402),
 ('love', -0.05974648892879486),
 ('machine', -0.11821285635232925)]