In [1]:
from scipy.stats import bernoulli

bernoulli.rvs(p=0.7,size=10)

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 0])

In [2]:
from scipy.stats import binom

binom.rvs(n=10,p=0.5,size=10)

array([5, 6, 5, 5, 4, 2, 4, 4, 7, 4])

In [3]:
import numpy as np

np.random.normal(
    loc=0,
    scale=1,
    size=1000
)

array([ 9.67639556e-01,  4.03880770e-01,  1.41116652e+00,  3.72095183e-01,
       -5.14394422e-02,  1.06361506e+00,  5.12405188e-01, -3.22753382e-01,
        6.75952078e-01, -7.76638061e-01,  1.45893063e-01, -4.20339624e-01,
        1.31795654e+00,  3.80859807e-01, -8.78930961e-01,  1.24327605e+00,
        7.09129321e-01, -8.15221491e-01,  9.94047947e-01,  2.14084923e-01,
        1.00096200e+00, -1.31732535e+00, -1.28741147e+00, -5.25184243e-01,
        4.26457605e-01,  1.07148790e-02, -6.51677092e-01, -1.98525408e+00,
        9.56318805e-01,  1.02638080e-02,  2.35808836e+00,  1.73280094e+00,
       -6.55463339e-01, -5.43109507e-01,  1.54211544e-02, -1.88826459e+00,
       -1.15330185e-01, -1.79041288e-01,  1.31611800e+00,  3.18288179e-01,
        4.26032248e-02,  6.20947643e-01,  6.32177755e-01,  1.01137116e-01,
        1.85585821e+00,  4.60541288e-01, -1.53371488e+00, -2.30606414e+00,
       -3.14038323e-01,  1.42766920e+00, -6.30599838e-01,  6.07752310e-01,
        6.96890954e-01, -

In [4]:
np.random.poisson(
    lam=5,
    size=1000
)

array([ 7,  7,  3,  4,  4,  5,  4,  8,  7,  3,  5,  3,  5,  6,  4,  8,  5,
        0,  5,  3,  5,  3,  6,  3, 10,  6,  3,  9,  3,  5,  8,  6,  3,  7,
        2,  5,  4,  3,  8,  7,  6,  3,  6,  8,  5,  6,  1,  8,  6,  1, 11,
        6,  8,  5,  7,  8,  3,  6,  5,  4,  6,  3,  3,  7,  8,  5,  5,  4,
        9,  4,  8,  2, 10,  6,  6,  5,  6,  0,  2,  5,  5,  5,  6,  6,  5,
        5,  8,  3,  0,  2,  7,  2,  5,  4,  5,  4,  4,  3,  5,  6,  5,  8,
        2,  5,  6,  5,  2,  5,  6, 12,  3,  7,  5,  0,  4,  5,  6,  8,  7,
        6,  5,  4,  3,  3,  6,  7,  6,  2,  4,  6,  4,  5,  2,  2,  2,  4,
        8,  2,  6,  4,  6,  2,  3,  3,  3,  3,  7,  8,  5,  2,  1,  5,  6,
        3,  6,  6,  5,  2,  4,  3,  5,  6,  9,  6,  8,  1,  4,  4,  7,  2,
        7,  6,  6,  4,  6,  9,  8,  5,  5,  6,  6,  4,  3,  4,  3,  4,  1,
        6,  5,  4,  7,  5,  3,  8,  3,  3,  1,  7,  6,  3,  6,  3,  5,  1,
        5,  7,  7,  5,  7,  5,  5,  4,  1,  3,  2,  7,  6,  5,  8,  5,  5,
        2,  4,  5,  3,  3

In [5]:
np.random.exponential(
    scale=1,
    size=1000
)

array([3.23850882e-01, 1.59116298e+00, 2.29217082e-01, 3.87715312e-01,
       8.33742217e-01, 8.55957537e-01, 3.38879943e-01, 1.04771018e+00,
       9.72121717e-01, 2.66077261e+00, 2.77571305e+00, 5.46963455e-01,
       7.01711738e-01, 1.05008959e+00, 8.90210886e-01, 1.61092107e+00,
       1.34734531e+00, 7.06874479e-01, 3.32485085e-01, 2.19211814e-01,
       3.08708516e+00, 1.92407708e+00, 5.44226237e-01, 1.19705017e+00,
       8.31233823e-03, 6.84429713e-02, 4.57258202e-01, 5.29350493e-01,
       6.07723051e-01, 1.53782518e+00, 1.72770381e+00, 3.79517095e-01,
       2.90910490e-01, 1.07921166e+00, 4.49582916e-01, 2.27543792e+00,
       7.74291039e-02, 1.56839166e+00, 1.15238852e+00, 1.80111486e+00,
       1.31904093e+00, 8.71262428e-04, 4.44526586e-02, 5.70549652e-01,
       4.00452124e+00, 1.77374738e-01, 1.81980771e+00, 1.65914317e+00,
       9.47584482e-01, 1.34880873e-01, 7.24772533e-01, 7.86617262e-01,
       1.70163209e+00, 2.72789599e-01, 1.00899828e+00, 1.15754906e+00,
      