In [1]:
import numpy as np

A = np.array([
    [1,2],
    [3,4]
])

print(A)

[[1 2]
 [3 4]]


In [2]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A + B)

[[ 6  8]
 [10 12]]


In [3]:
A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

print(A @ B)

[[19 22]
 [43 50]]


In [4]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np

X = np.array([[1,2]])

W = np.array([
    [0.5,0.2],
    [0.3,0.7]
])

Z = X @ W

print(Z)

[[1.1 1.6]]
