In [1]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
!pip install transformers datasets accelerate
!pip install langchain langchain-community langchain-openai
!pip install fastapi uvicorn
!pip install n8n


Looking in indexes: https://download.pytorch.org/whl/cpu
  Using cached dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Using cached dill-0.4.0-py3-none-any.whl (119 kB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   --- ------------------------------------ 2.6/27.5 MB 12.6 MB/s eta 0:00:02
   --------- ------------------------------ 6.8/27.5 MB 16.1 MB/s eta 0:00:02
   --------------- ------------------------ 11.0/27.5 MB 17.6 MB/s eta 0:00:01
   ----------------------- ---------------- 16.0/27.5 MB 19.0 MB/s eta 0:00:01
   ----------------------------- ---------- 20.2/27.5 MB 19.3 MB/s eta 0:00:01
   ----------------------------------- ---- 24.1/27.5 MB 19.1 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.5 MB 19.2 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 17.8 MB/s eta 0:00:00

   -------- ------------------------------- 1/5 [pyarrow]
   -------- ------------------------------- 1/5 [pyarrow]
   -------- ----

1. Tensors & Autograd

✔ tensors, dtype, device
✔ .requires_grad, .backward()

In [2]:
import torch

x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x.pow(2).sum()
y.backward()
x.grad


tensor([4., 6.])

2. Neural Networks with nn.Module

✔ Linear, ReLU
✔ forward pass

In [3]:
import torch.nn as nn

class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(10, 1)

    def forward(self, x):
        return self.fc(x)


3. Training Loop (VERY IMPORTANT)

✔ loss
✔ optimizer
✔ backward + step

In [4]:
model = SimpleNet()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nn.MSELoss()

for epoch in range(100):
    x = torch.randn(32, 10)
    y = torch.randn(32, 1)

    pred = model(x)
    loss = loss_fn(pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


4. Datasets & DataLoader

✔ custom dataset
✔ batching

In [5]:
from torch.utils.data import Dataset, DataLoader


Creating tensors

In [6]:
a = torch.zeros(3, 4)
b = torch.ones(2, 2)
c = torch.randn(3, 3)  # normal distribution

a, b, c


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[ 0.2987, -0.5814,  0.0021],
         [ 0.1655,  1.0190, -1.8177],
         [-0.5019,  0.3718, -0.3550]]))

Tensor Operations

In [7]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print(x + y)
print(x * y)
print(torch.dot(x, y))


tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)


The MOST IMPORTANT CONCEPT: Autograd

In [8]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3*x + 1

y.backward()
print(x.grad)


tensor(7.)


Multiple Variables

In [9]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

z = x*y + y**2
z.backward()

print("dz/dx:", x.grad)
print("dz/dy:", y.grad)


dz/dx: tensor(3.)
dz/dy: tensor(8.)


Linear Regression from scratch

In [17]:
import torch
torch.manual_seed(42)

x = torch.randn(100, 1)
y = 3 * x + 2 + 0.1 * torch.randn(100, 1)
x[:5], y[:5]
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

w, b
y_pred = w * x + b
y_pred[:5]
loss = ((y_pred - y) ** 2).mean()
loss
loss.backward()

print("dw:", w.grad)
print("db:", b.grad)
lr = 0.1

with torch.no_grad():
    w -= lr * w.grad
    b -= lr * b.grad

w.grad = None
b.grad = None


w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

lr = 0.1
epochs = 100

for epoch in range(epochs):
    y_pred = w * x + b
    loss = ((y_pred - y) ** 2).mean()
    
    loss.backward()
    
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
    w.grad = None
    b.grad = None
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}: loss={loss.item():.4f}")
print("Learned w:", w.item())
print("Learned b:", b.item())


dw: tensor([-5.3079])
db: tensor([-4.7484])
Epoch 0: loss=8.7921
Epoch 10: loss=0.0884
Epoch 20: loss=0.0085
Epoch 30: loss=0.0078
Epoch 40: loss=0.0078
Epoch 50: loss=0.0078
Epoch 60: loss=0.0078
Epoch 70: loss=0.0078
Epoch 80: loss=0.0078
Epoch 90: loss=0.0078
Learned w: 3.001180648803711
Learned b: 2.0035669803619385
