In [1]:
import numpy as np

# 2D array = features (rows = samples, cols = features)
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Shape:", X.shape)
print("First row:", X[0])
print("Column sum:", X.sum(axis=0))
print("Mean of all elements:", X.mean())


Shape: (3, 3)
First row: [1 2 3]
Column sum: [12 15 18]
Mean of all elements: 5.0


In [2]:
import numpy as np

# Fake features extracted from packet capture (bytes, duration, flags)
X = np.array([
    [120, 2.5, 1],   # benign
    [340, 1.2, 0],   # benign
    [560, 3.0, 1],   # malicious
    [80,  0.5, 0],   # benign
    [10,  5.5, 1]    # malicious
])


In [3]:
print(X.shape)   # (5,3) → 5 samples, 3 features
print(X[0])      # first row
print(X[:,0])    # first column (bytes)


(5, 3)
[120.    2.5   1. ]
[120. 340. 560.  80.  10.]


In [4]:
print("Mean bytes:", X[:,0].mean())
print("Max duration:", X[:,1].max())
print("Sum of flags:", X[:,2].sum())


Mean bytes: 222.0
Max duration: 5.5
Sum of flags: 3.0


In [5]:
print("Bytes doubled:", X[:,0] * 2)
print("Normalize durations:", (X[:,1] - X[:,1].mean()) / X[:,1].std())


Bytes doubled: [ 240.  680. 1120.  160.   20.]
Normalize durations: [-0.02314654 -0.77540895  0.26618516 -1.18047333  1.71284365]


In [6]:
print("Flows > 200 bytes:\n", X[X[:,0] > 200])


Flows > 200 bytes:
 [[340.    1.2   0. ]
 [560.    3.    1. ]]


In [7]:
y = np.array([0,0,1,0,1])  # labels (benign=0, malicious=1)
dataset = np.column_stack((X, y))
print("Dataset with labels:\n", dataset)



Dataset with labels:
 [[1.2e+02 2.5e+00 1.0e+00 0.0e+00]
 [3.4e+02 1.2e+00 0.0e+00 0.0e+00]
 [5.6e+02 3.0e+00 1.0e+00 1.0e+00]
 [8.0e+01 5.0e-01 0.0e+00 0.0e+00]
 [1.0e+01 5.5e+00 1.0e+00 1.0e+00]]


In [8]:
samples = np.random.choice(X[:,0], size=3, replace=False)
print("Random bytes sample:", samples)


Random bytes sample: [340. 560. 120.]
